function [scenario, egoVehicle] = helperSimpleHighwayScenarioDSD()
    % createDrivingScenario Returns the drivingScenario defined in the Designer
    
    % Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.2 (R2021b).
    % Generated on: 18-Dec-2020 13:15:15
    
    % Construct a drivingScenario object.
    scenario = drivingScenario('SampleTime', 0.1);
    
    % Add all road segments
    roadCenters = [-1 0 0;
        257 0 0];
    laneSpecification = lanespec(3);
    road1 = road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');
    
    % Add the barriers
    barrier(scenario, road1, 'RoadEdge', 'right', ...
        'ClassID', 6, ...
        'Width', 0.433, ...
        'Mesh', driving.scenario.guardrailMesh, 'PlotColor', [0.55 0.55 0.55], 'Name', 'Guardrail');
    
    % Add the ego vehicle
    egoVehicle = vehicle(scenario, ...
        'ClassID', 1, ...
        'Position', [0 0 0], ...
        'FrontOverhang', 0.9, ...
        'Mesh', driving.scenario.carMesh, ...
        'Name', 'Car');
    waypoints = [1 0 0;
        240 0 0];
    speed = [25;25];
    waittime = [0;0];
    trajectory(egoVehicle, waypoints, speed, waittime);
    
    % Add the non-ego actors
    car1 = vehicle(scenario, ...
        'ClassID', 1, ...
        'Position', [30 3.6 0], ...
        'FrontOverhang', 0.9, ...
        'Mesh', driving.scenario.carMesh, ...
        'Name', 'Car1');
    waypoints = [30 3.6 0;
        100 3.6 0;
        100.1 3.6 0;
        150 0 0;
        150.1 0 0;
        250 0 0];
    speed = [30;25;25;25;25;25];
    waittime = [0;0;0;0;0;0];
    trajectory(car1, waypoints, speed, waittime);
    
    